plugins {
    id "com.android.application"
}

android {
    namespace "com.andropy.ide"
    compileSdk 34
    ndkVersion "25.2.9519653"

    buildFeatures {
        buildConfig true
    }

    defaultConfig {
        applicationId "com.andropy.ide"
        minSdk 26
        targetSdk 28
        versionCode 1
        versionName "0.1.0"

        ndk {
            abiFilters "x86_64", "arm64-v8a"
        }
    }

    buildTypes {
        debug {
            buildConfigField "boolean", "ANDROPY_PREBUNDLED_RUNTIME", "true"
            buildConfigField "boolean", "ANDROPY_SKIP_RUNTIME_CHECK", "true"
        }
        release {
            buildConfigField "boolean", "ANDROPY_PREBUNDLED_RUNTIME", "false"
            buildConfigField "boolean", "ANDROPY_SKIP_RUNTIME_CHECK", "false"
        }
    }

    sourceSets {
        debug {
            assets.srcDirs += ["../release-assets/runtime-v9"]
        }
    }

}

dependencies {
    implementation "com.termux.termux-app:terminal-view:0.118.0"
    implementation "com.github.luben:zstd-jni:1.5.7-9@aar"
}
